apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ojq7w2aix-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ojq7w2aix-nodejs 
  name: ojq7w2aix-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ojq7w2aix-nodejs 
